src/main/java/trinity/play2learn/backend/admin/year/controllers/YearRegisterController.java, src/main/java/trinity/play2learn/backend/admin/year/dtos/YearRequestDto.java, src/main/java/trinity/play2learn/backend/admin/year/dtos/YearResponseDto.java, src/main/java/trinity/play2learn/backend/admin/year/mappers/YearMapper.java, src/main/java/trinity/play2learn/backend/admin/year/models/Year.java, src/main/java/trinity/play2learn/backend/admin/year/repositories/IYearRepository.java, src/main/java/trinity/play2learn/backend/admin/year/services/YearRegisterService.java, src/main/java/trinity/play2learn/backend/admin/year/services/commons/YearExistService.java, src/main/java/trinity/play2learn/backend/admin/year/services/interfaces/IYearExistService.java, src/main/java/trinity/play2learn/backend/admin/year/services/interfaces/IYearRegisterService.java, src/main/java/trinity/play2learn/backend/configs/exceptions/GlobalExceptionHandler.java, src/main/java/trinity/play2learn/backend/configs/security/SecurityConfig.java, src/main/java/trinity/play2learn/backend/pruebaConfigs/TestController.java, src/main/java/trinity/play2learn/backend/user/repository/IUserRepository.java
El mismo implementa:
- Controlador
- Service de CU
- Service para validar duplicado
- Repository de Year
- Model Year
- Dto de year para request y response
- Mapper de year.
El endpoint contempla las validaciones definidas en la userstory
=> feat Endpoint para crear un año

src/main/java/trinity/play2learn/backend/admin/classes/repositories/IClassRepository.java, src/main/java/trinity/play2learn/backend/admin/classes/services/commons/ClassGetByIdService.java, src/main/java/trinity/play2learn/backend/admin/classes/services/interfaces/IClassGetByIdService.java, src/main/java/trinity/play2learn/backend/admin/student/controllers/StudentRegisterController.java, src/main/java/trinity/play2learn/backend/admin/student/dtos/StudentRequestDto.java, src/main/java/trinity/play2learn/backend/admin/student/dtos/StudentResponseDto.java, src/main/java/trinity/play2learn/backend/admin/student/mappers/StudentMapper.java, src/main/java/trinity/play2learn/backend/admin/student/models/Studen.java, src/main/java/trinity/play2learn/backend/admin/student/models/Student.java, src/main/java/trinity/play2learn/backend/admin/student/repositories/IStudentRepository.java, src/main/java/trinity/play2learn/backend/admin/student/services/StudentRegisterService.java, src/main/java/trinity/play2learn/backend/admin/student/services/interfaces/IStudentRegisterService.java, src/main/java/trinity/play2learn/backend/user/dtos/user/UserResponseDto.java, src/main/java/trinity/play2learn/backend/user/mapper/UserMapper.java, src/main/java/trinity/play2learn/backend/user/repository/IUserRepository.java, src/main/java/trinity/play2learn/backend/user/services/user/commons/UserCreateService.java, src/main/java/trinity/play2learn/backend/user/services/user/commons/UserExistsService.java, src/main/java/trinity/play2learn/backend/user/services/user/interfaces/IUserCreateService.java, src/main/java/trinity/play2learn/backend/user/services/user/interfaces/IUserExistService.java, src/test/java/trinity/play2learn/backend/student/registerStudent/StudentRegisterControllerTest.java
Tiene toda la lógica para registrar un estudiante y los test correspondientes
=> 32 endpoint para crear un estudiante

Dockerfile
Modifique el dockerfile para poder subirlo al server, no tiene mas importancia.
=> 38 subir backend al server

src/main/java/trinity/play2learn/backend/admin/student/models/Student.java, src/main/java/trinity/play2learn/backend/admin/student/services/StudentRegisterService.java, src/main/java/trinity/play2learn/backend/admin/teacher/controllers/TeacherRegisterController.java, src/main/java/trinity/play2learn/backend/admin/teacher/dtos/TeacherRequestDto.java, src/main/java/trinity/play2learn/backend/admin/teacher/dtos/TeacherResponseDto.java, src/main/java/trinity/play2learn/backend/admin/teacher/mapper/TeacherMapper.java, src/main/java/trinity/play2learn/backend/admin/teacher/models/Teacher.java, src/main/java/trinity/play2learn/backend/admin/teacher/repositories/ITeacherRepository.java, src/main/java/trinity/play2learn/backend/admin/teacher/services/TeacherRegisterService.java, src/main/java/trinity/play2learn/backend/admin/teacher/services/interfaces/ITeacherRegisterService.java, src/main/java/trinity/play2learn/backend/user/services/user/commons/UserCreateService.java, src/main/java/trinity/play2learn/backend/user/services/user/commons/UserExistsService.java
Cree el endpoint para registrar un docente. Ademas, fixee algunas cosas del endpoint para registrar un estudiante.
=> 33 endpoint para crear un docente

src/main/java/trinity/play2learn/backend/admin/course/controllers/CourseListController.java, src/main/java/trinity/play2learn/backend/admin/course/mappers/CourseMapper.java, src/main/java/trinity/play2learn/backend/admin/course/models/Course.java, src/main/java/trinity/play2learn/backend/admin/course/repositories/ICourseRepository.java, src/main/java/trinity/play2learn/backend/admin/course/services/CourseListService.java, src/main/java/trinity/play2learn/backend/admin/course/services/interfaces/ICourseListService.java, src/main/java/trinity/play2learn/backend/admin/year/mappers/YearMapper.java, src/main/java/trinity/play2learn/backend/admin/year/services/YearListService.java
Agrege un endpoint para listar todos los cursos no eliminados.
=> 45 agregar endpoint get para listar años adminyears

src/test/java/trinity/play2learn/backend/admin/student/registerStudent/StudentRegisterControllerTest.java, src/test/java/trinity/play2learn/backend/admin/teacher/registerTeacher/TeacherRegisterControllerTest.java
Realize el testeo del endpoint Registar un docente. Todos los test fueron exitosos.
Closes #48
=> feat: Test de endpoint Registrar un docente. #48

src/main/java/trinity/play2learn/backend/admin/year/controllers/YearUpdateController.java, src/main/java/trinity/play2learn/backend/admin/year/dtos/YearUpdateRequestDto.java, src/main/java/trinity/play2learn/backend/admin/year/services/YearUpdateService.java, src/main/java/trinity/play2learn/backend/admin/year/services/interfaces/IYearUpdateService.java
El mismo contiene:
- YearUpdateRequestDto
- Service
- Controller
=> feat Update Year

src/main/java/trinity/play2learn/backend/admin/subject/repositories/ISubjectRepository.java, src/main/java/trinity/play2learn/backend/admin/subject/services/SubjectRegisterService.java, src/main/java/trinity/play2learn/backend/admin/subject/services/commons/ValidateSubjectService.java, src/main/java/trinity/play2learn/backend/admin/subject/services/interfaces/IValidateSubjectService.java
Agregue validacion de materia con nombre y curso repetidos en el servicio.
=> feat: Agregue validacion de materia con nombre y curso repetido.

src/main/java/trinity/play2learn/backend/admin/subject/controllers/SubjectListPaginatedController.java, src/main/java/trinity/play2learn/backend/admin/subject/mappers/SubjectMapper.java, src/main/java/trinity/play2learn/backend/admin/subject/repositories/ISubjectPaginatedRepository.java, src/main/java/trinity/play2learn/backend/admin/subject/services/SubjectListPaginatedService.java, src/main/java/trinity/play2learn/backend/admin/subject/services/interfaces/ISubjectListPaginatedService.java, src/main/java/trinity/play2learn/backend/admin/subject/specs/SubjectSpecs.java
Cree un endpoint para listar materias con paginacion
=> feat: Listar materias con paginacion. #92

src/main/java/trinity/play2learn/backend/admin/subject/mappers/SubjectMapper.java, src/main/java/trinity/play2learn/backend/admin/subject/repositories/ISubjectRepository.java, src/main/java/trinity/play2learn/backend/admin/subject/services/SubjectUpdateService.java, src/main/java/trinity/play2learn/backend/admin/subject/services/commons/ValidateSubjectService.java, src/main/java/trinity/play2learn/backend/admin/subject/services/interfaces/IValidateSubjectService.java, src/main/java/trinity/play2learn/backend/admin/year/repositories/IYearRepository.java, src/main/java/trinity/play2learn/backend/admin/year/services/YearUpdateService.java, src/main/java/trinity/play2learn/backend/admin/year/services/commons/YearExistService.java, src/main/java/trinity/play2learn/backend/admin/year/services/interfaces/IYearExistService.java
Arregle los update de Materia y año. Los mismos devolvian un error si actualizabas una materia con el mismo nombre que ya tenian. Ahora devuelven un 200 ok en esos casos.
=> Fix update

src/main/java/trinity/play2learn/backend/admin/course/controllers/CourseDeleteController.java, src/main/java/trinity/play2learn/backend/admin/course/services/CourseDeleteService.java, src/main/java/trinity/play2learn/backend/admin/course/services/interfaces/ICourseDeleteService.java, src/main/java/trinity/play2learn/backend/admin/subject/repositories/ISubjectRepository.java, src/main/java/trinity/play2learn/backend/admin/subject/services/commons/SubjectExistsByCourseService.java, src/main/java/trinity/play2learn/backend/admin/subject/services/interfaces/ISubjectsExistsByCourseService.java
Se debe poder eliminar un curso, siempre y cuando no tenga materias ni estudiantes asignados.
=> feat: Endpoint para eliminar un curso. #113

src/main/java/trinity/play2learn/backend/activity/ahorcado/mappers/AhorcadoMapper.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/controllers/ClasificacionActivityGenerateController.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/dtos/request/CategoryClasificacionRequestDto.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/dtos/request/ClasificacionActivityRequestDto.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/dtos/request/ConceptClasificacionRequestDto.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/dtos/response/CategoryClasificacionResponseDto.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/dtos/response/ClasificacionActivityResponseDto.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/dtos/response/ConceptClasificacionResponseDto.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/mappers/CategoryClasificacionMapper.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/mappers/ClasificacionActivityMapper.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/mappers/ConceptClasificacionMapper.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/models/CategoryClasificacion.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/models/ClasificacionActivity.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/models/ConceptClasificacion.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/repositories/IClasificacionActivityRepository.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/services/ClasificacionActivityGenerateService.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/services/commons/ClasificacionValidateCategoriesNamesService.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/services/commons/ClasificacionValidateConceptsNamesService.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/services/commons/ValidateStringListService.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/services/interfaces/IClasificacionGenerateService.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/services/interfaces/IClasificacionValidateCategoriesNamesService.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/services/interfaces/IClasificacionValidateConceptsNamesService.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/services/interfaces/IValidateStringListService.java
El endpoint espera un JSON tal que asi:
```json
{
"description": "Clasifica los siguientes objetos en frutas o verduras",
"startDate": "2025-07-22T10:00:00",
"endDate": "2025-07-22T11:00:00",
"dificulty": "MEDIO",
"maxTime": 60,
"subjectId": 7,
"attempts": 5,
"maxTimePerQuestionInSeconds": 15,
"categories": [
{
"name": "Frutas",
"concepts": [
{
"name": "Manzana"
},
{
"name": "Banana"
},
{
"name": "Pera"
}
]
},
{
"name": "Verduras",
"concepts": [
{
"name": "Lechuga"
},
{
"name": "Zanahoria"
}
]
}
]
}
````
Y, de no lanzar errores, devuelve un json como este:
```json
{
"data": {
"id": 4,
"name": "Desafio de clasificacion",
"description": "Clasifica los siguientes objetos en frutas o verduras",
"startDate": "2025-07-22T10:00:00",
"endDate": "2025-07-22T11:00:00",
"dificulty": "MEDIO", …
```
=> feat: Cree un endpoint para generar una actividad del tipo Clasificacion. #131

pom.xml, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/controllers/OrdenarSecuenciaGenerateController.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/dtos/request/EventRequestDto.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/dtos/request/OrdenarSecuenciaRequestDto.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/dtos/response/EventResponseDto.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/dtos/response/OrdenarSecuenciaResponseDto.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/mappers/EventMapper.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/mappers/OrdenarSecuenciaMapper.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/mappers/OrdenarSecuenciaRequestMapper.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/mappers/Static.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/models/Event.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/models/OrdenarSecuencia.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/repositories/IEventRepository.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/repositories/IOrdenarSecuenciaRepository.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/services/OrdenarSecuenciaActivityGenerateService.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/services/commons/EventsGenerateService.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/services/commons/ValidateEvents.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/services/interfaces/IEventsGenerateService.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/services/interfaces/IOrdenarSecuenciaActivityGenerateService.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/services/interfaces/IValidateEvents.java, src/main/java/trinity/play2learn/backend/utils/DtoValidator.java
Generar Ordenar Secuencia
El mismo recibe un formdata con:
- payload
El payload es un json con todos los datos de la actividad:
```json
{
"description": "Secuencia de eventos de la Revolución Francesa",
"startDate": "2025-07-22T10:33:00",
"endDate": "2025-08-22T10:33:00",
"dificulty": "MEDIO",
"maxTime": 60,
"subjectId": 3,
"attempts": 3,
"events": [
{
"name": "Toma de la Bastilla",
"description": "14 de julio de 1789",
"order": 1
},
{
"name": "Declaración de los Derechos del Hombre",
"description": "26 de agosto de 1789",
"order": 2
},
{
"name": "Ejecución de Luis XVI",
"description": "21 de enero de 1793",
"order": 3
}
]
}
```
El payload es un atributo del formdata de tipo Text, donde envia el json como un string.
Los otros atributos del formdata son las imagenes, enviadas como file. …
=> 128 crear endpoint para generar actividad ordenar secuencias

src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/controllers/ArbolDeDecisionGenerateController.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/dtos/request/ArbolDeDecisionActivityRequestDto.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/dtos/request/ConsecuenceArbolDecisionRequestDto.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/dtos/request/DecisionArbolDecisionRequestDto.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/dtos/response/ArbolDeDecisionActivityResponseDto.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/dtos/response/ConsecuenceArbolDecisionResponseDto.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/dtos/response/DecisionArbolDecisionResponseDto.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/mappers/ArbolDeDecisionMapper.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/mappers/ConsecuenceArbolDecisionMapper.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/mappers/DecisionArbolDecisionMapper.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/models/ArbolDeDecisionActivity.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/models/ConsecuenceArbolDecision.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/models/DecisionArbolDecision.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/repositories/IArbolDeDecisionRepository.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/services/ArbolDecisionGenerateService.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/services/interfaces/IArbolDecisionGenerateService.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/services/interfaces/IArbolDecisionValidateDecisionTreeService.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/services/interfaces/IDecisionArbolDecisionValidateService.java, src/main/java/trinity/play2learn/backend/configs/messages/ValidationMessages.java
- El docente deberá ingresar una introducción de la situación sobre la que se tomarán las decisiones.
- El docente deberá ingresar dos opciones posibles que el alumno podrá tomar.
- Si presiona el botón de “Siguiente decisión”, podrá ingresar nuevamente dos opciones posibles para cada camino o podrá ingresar una consecuencia del camino.
- Cuando ingresa una consecuencia, el docente podrá tildar un checkbox de “Actividad desaprobada”. Esto significa que los alumnos que lleguen a esta consecuencia desaprobaran la actividad.
- La decisión tendrá un máximo de 200 caracteres.
- La consecuencia tendrá un máximo de 200 caracteres.
- Cada decision debe tener 2 o ninguna opcion.
- Cada decision debe tener opciones o consecuencia.
El endpoint espera un JSON como este:
```json
{
"description": "Toma …
```
=> feat: Cree endpoint para generar una actividad Arbol de decision. #145

src/main/java/trinity/play2learn/backend/admin/student/dtos/StudentResponseDto.java, src/main/java/trinity/play2learn/backend/admin/student/mappers/StudentMapper.java, src/main/java/trinity/play2learn/backend/admin/student/models/Student.java, src/main/java/trinity/play2learn/backend/admin/student/services/StudentRegisterService.java, src/main/java/trinity/play2learn/backend/profile/avatar/models/TypeAspect.java, src/main/java/trinity/play2learn/backend/profile/avatar/services/commons/AspectGetByIdService.java, src/main/java/trinity/play2learn/backend/profile/avatar/services/interfaces/IAspectGetByIdService.java, src/main/java/trinity/play2learn/backend/profile/profile/controllers/AddAspectToInventoryController.java, src/main/java/trinity/play2learn/backend/profile/profile/controllers/SelectAspectController.java, src/main/java/trinity/play2learn/backend/profile/profile/dtos/request/AddAspectRequestDto.java, src/main/java/trinity/play2learn/backend/profile/profile/dtos/response/ProfileResponseDto.java, src/main/java/trinity/play2learn/backend/profile/profile/mappers/ProfileMapper.java, src/main/java/trinity/play2learn/backend/profile/profile/models/Profile.java, src/main/java/trinity/play2learn/backend/profile/profile/repositories/IProfileRepository.java, src/main/java/trinity/play2learn/backend/profile/profile/services/ProfileAddAspectToInventoryService.java, src/main/java/trinity/play2learn/backend/profile/profile/services/ProfileGenerateService.java, src/main/java/trinity/play2learn/backend/profile/profile/services/ProfileSelectAspectService.java, src/main/java/trinity/play2learn/backend/profile/profile/services/commons/ProfileGetById.java, src/main/java/trinity/play2learn/backend/profile/profile/services/interfaces/IProfileAddAspectToInventoryService.java, src/main/java/trinity/play2learn/backend/profile/profile/services/interfaces/IProfileGenerateService.java, src/main/java/trinity/play2learn/backend/profile/profile/services/interfaces/IProfileGetByIdService.java, src/main/java/trinity/play2learn/backend/profile/profile/services/interfaces/IProfileSelectAspectService.java
La primera funcionalidad que hice es la de generar un perfil de un estudiante, la misma esta anexada a cuando se genera un estudiante en el sistema.
El perfil del estudiante por el momento tiene:
- El cuerpo seleccionado.
- La remera seleccionada.
- El sombrero seleccionado.
- El inventario con todos los aspectos comprados por el estudiante.
Todos estos valores se inician en null cuando se genera.
Y se retorna un dto del mismo junto con el estudiante:
```json
{
"id": 27,
"name": "Mauricio",
"lastname": "Macri",
"dni": "20400433",
"user": {
"id": 59,
"email": "maurimacri@gmail.com"
},
"course": {
"id": 2,
"name": "Matematica",
"year": {
"id": 8,
"name": "Sexto Año"
}
},
"active": true,
"profile": {
"id": 1,
"selectedBody": {
"id": 3,
"name": "Cuerpo Masculino Castaño",
"image": …
```
=> 155 crear perfil de un estudiante

src/main/java/trinity/play2learn/backend/admin/student/services/StudentRegisterService.java, src/main/java/trinity/play2learn/backend/benefits/controllers/BenefitListController.java, src/main/java/trinity/play2learn/backend/benefits/controllers/BenefitListPaginatedController.java, src/main/java/trinity/play2learn/backend/benefits/repositories/IBenefitPaginatedRepository.java, src/main/java/trinity/play2learn/backend/benefits/services/BenefitListByTeacherPaginatedService.java, src/main/java/trinity/play2learn/backend/benefits/services/BenefitListByTeacherService.java, src/main/java/trinity/play2learn/backend/benefits/services/interfaces/IBenefitListByTeacherPaginatedService.java, src/main/java/trinity/play2learn/backend/benefits/services/interfaces/IBenefitListByTeacherService.java, src/main/java/trinity/play2learn/backend/benefits/specs/BenefitSpecs.java
El mismo se accede mediante la URL `/benefits/teacher/paginated`. 
Devuelve un listado de los beneficios del docente que realiza la peticion con los filtros correspondientes recibidos.
=> feat: Cree endpoint para listar beneficios por docente con paginacion

src/main/java/trinity/play2learn/backend/admin/subject/controllers/SubjectAssignTeacherController.java, src/main/java/trinity/play2learn/backend/admin/subject/dtos/SubjectAssignTeacherRequestDto.java, src/main/java/trinity/play2learn/backend/admin/subject/services/SubjectAssignTeacherService.java, src/main/java/trinity/play2learn/backend/admin/subject/services/interfaces/ISubjectAssignTeacherService.java
Cambie endpoint AssignTeacher para que espere un dto con el id de la materia y el docente en lugar de recibirlos mediante la URL. El JSON que espera es el siguiente:
```json
{
"subjectId": 3,
"teacherId": 12
}
=> refactoring: Endpoint assignTeacher espera dto. #176

src/main/java/trinity/play2learn/backend/profile/avatar/models/TypeAspect.java, src/main/java/trinity/play2learn/backend/profile/profile/dtos/request/UnselectAspectRequestDto.java, src/main/java/trinity/play2learn/backend/profile/profile/services/ProfileAddAspectToInventoryService.java, src/main/java/trinity/play2learn/backend/profile/profile/services/ProfileSelectAspectService.java, src/main/java/trinity/play2learn/backend/profile/profile/services/ProfileUnselectAspectService.java
Cambie la logica del unselect aspect para implementarla mediente el patron strategy.
=> refact Unselect aspect

src/main/java/trinity/play2learn/backend/activity/activity/dtos/activityStudent/ActivityStudentApprovedResponseDto.java, src/main/java/trinity/play2learn/backend/activity/activity/dtos/activityStudent/ActivityStudentNotApprovedResponseDto.java, src/main/java/trinity/play2learn/backend/activity/activity/mappers/ActivityMapper.java
Realize dos cambios en el DTO de actividades aprobadas por el estudiante:
- Cambie atributo dificulty por difficulty
- Agregue atributo state que trae siempre `APPROVE`
=> 204 fix endpoint get de actividades aprobadas

src/main/java/trinity/play2learn/backend/activity/activity/controllers/ActivityGetController.java, src/main/java/trinity/play2learn/backend/activity/activity/mappers/IActivityMapper.java, src/main/java/trinity/play2learn/backend/activity/activity/services/ActivityGetService.java, src/main/java/trinity/play2learn/backend/activity/activity/services/commons/ActivityGetByIdService.java, src/main/java/trinity/play2learn/backend/activity/activity/services/interfaces/IActivityGetService.java, src/main/java/trinity/play2learn/backend/activity/ahorcado/mappers/AhorcadoMapper.java, src/main/java/trinity/play2learn/backend/activity/arbolDeDecision/mappers/ArbolDeDecisionMapper.java, src/main/java/trinity/play2learn/backend/activity/clasificacion/mappers/ClasificacionActivityMapper.java, src/main/java/trinity/play2learn/backend/activity/completarOracion/mappers/CompletarOracionActivityMapper.java, src/main/java/trinity/play2learn/backend/activity/memorama/mappers/MemoramaMapper.java, src/main/java/trinity/play2learn/backend/activity/noLudica/mappers/NoLudicaMapper.java, src/main/java/trinity/play2learn/backend/activity/ordenarSecuencia/mappers/OrdenarSecuenciaMapper.java, src/main/java/trinity/play2learn/backend/activity/preguntados/Mappers/PreguntadosMapper.java
Cree un endpoint para obtener todos los datos de una actividad mediante su ID. El mismo sera accedido solo por un estudiante mediante la URI `GET` `/activity/{id}`. 
El mismo devuelve un JSON como este:
```json
{
"data": {
"id": 1,
"name": "Preguntados",
"description": "Response las siguientes preguntas sobre Argentina!",
"startDate": "2025-07-22T10:00:00",
"endDate": "2025-07-22T11:00:00",
"dificulty": "MEDIO",
"maxTime": 60,
"subject": {
"id": 1,
"name": "Matematica",
"course": {
"id": 1,
"name": "A",
"year": {
"id": 1,
"name": "Primer Año"
}
},
"teacher": {
"id": 6,
"name": "Rene",
"lastname": "Iglesias",
"dni": "33220711",
"user": {
"id": 8,
"email": "reneiglesias753@gmail.com"
},
"active": true
},
"optional": false,
"actualBalance": 4000.0,
"initialBalance": 70000.0,
"students": [
{ …
```
=> feat: Endpoint GetActivityById. #202

src/main/java/trinity/play2learn/backend/activity/activity/mappers/ActivityCompletedMapper.java, src/main/java/trinity/play2learn/backend/activity/activity/models/activity/TypeReward.java, src/main/java/trinity/play2learn/backend/activity/activity/services/commons/ActivityCreateNotApprovedDtosService.java
Agregue la logica del calculo de la posible recompensa al get de actividades no aprobadas
=> feat Calculo de recompensa posible

src/main/java/trinity/play2learn/backend/activity/activity/repositories/IActivityCompletedRepository.java, src/main/java/trinity/play2learn/backend/activity/activity/services/commons/ActivityCalculateTotalRealizationsService.java, src/main/java/trinity/play2learn/backend/activity/activity/services/interfaces/IActivityCalculateTotalRealizationsService.java, src/main/java/trinity/play2learn/backend/admin/course/repositories/ICourseRepository.java, src/main/java/trinity/play2learn/backend/admin/student/repositories/IStudentRepository.java, src/main/java/trinity/play2learn/backend/admin/subject/repositories/ISubjectRepository.java, src/main/java/trinity/play2learn/backend/admin/teacher/repositories/ITeacherRepository.java, src/main/java/trinity/play2learn/backend/admin/year/repositories/IYearRepository.java, src/main/java/trinity/play2learn/backend/profile/profile/services/ProfileAddAspectToInventoryService.java, src/main/java/trinity/play2learn/backend/pruebaConfigs/TestController.java, src/main/java/trinity/play2learn/backend/statistics/home/controllers/StatisticsHomeAdminController.java, src/main/java/trinity/play2learn/backend/statistics/home/controllers/StatisticsHomeTeacherController.java, src/main/java/trinity/play2learn/backend/statistics/home/dtos/response/StatisticsActivityDataDto.java, src/main/java/trinity/play2learn/backend/statistics/home/dtos/response/StatisticsHomeAdminResponseDto.java, src/main/java/trinity/play2learn/backend/statistics/home/dtos/response/StatisticsHomeTeacherResponseDto.java, src/main/java/trinity/play2learn/backend/statistics/home/dtos/response/StatisticsSubjectDataDto.java, src/main/java/trinity/play2learn/backend/statistics/home/mappers/StatisticsActivityDataMapper.java, src/main/java/trinity/play2learn/backend/statistics/home/mappers/StatisticsHomeAdminMapper.java, src/main/java/trinity/play2learn/backend/statistics/home/mappers/StatisticsHomeTeacherMapper.java, src/main/java/trinity/play2learn/backend/statistics/home/mappers/StatisticsSubjectDataMapper.java, src/main/java/trinity/play2learn/backend/statistics/home/services/StatisticsHomeAdminService.java, src/main/java/trinity/play2learn/backend/statistics/home/services/StatisticsHomeTeacherService.java, src/main/java/trinity/play2learn/backend/statistics/home/services/commons/StatisticsTotalCoursesByTeacherService.java, src/main/java/trinity/play2learn/backend/statistics/home/services/commons/StatisticsTotalStudentsByTeacherService.java, src/main/java/trinity/play2learn/backend/statistics/home/services/interfaces/IStatisticsHomeAdminService.java, src/main/java/trinity/play2learn/backend/statistics/home/services/interfaces/IStatisticsHomeTeacherService.java, src/main/java/trinity/play2learn/backend/statistics/home/services/interfaces/IStatisticsTotalCoursesByTeacherService.java, src/main/java/trinity/play2learn/backend/statistics/home/services/interfaces/IStatisticsTotalStudentsByTeacherService.java
Agregue dos endpoints para obtener estadisticas usables en los home tanto del admin como del teacher.
El home del admin es accedido desde la url "/statistics/home/admin", que tiene autenticacion y deja pasar solo a un usuario admin, la misma retorna:
```json
{
"data": {
"totalStudents": 71,
"totalTeachers": 10,
"totalYears": 6,
"totalCourses": 18,
"reserveTotalBalance": 930000.0,
"reserveTotalBalanceOnCirculation": 930000.0,
"reserveTotalBalanceOnReserve": 0.0
},
"message": "OK",
"errors": null,
"timestamp": "2025-09-10T13:12:32.304274300Z"
}
```
El segundo endpoint, es accedido unicamente por un teacher, mediante la autenticacion se busca el usuario asociado y asi los datos del teacher, la url es "/statistics/home/teacher" y retorna lo siguiente:
```json
{
"data": {
"totalStudents": 32, …
```
=> feat Estadisticas home teacher y admin

src/main/java/trinity/play2learn/backend/student/controllers/StudentGetConrtollerService.java, src/main/java/trinity/play2learn/backend/student/services/StudentGetByTokenService.java, src/main/java/trinity/play2learn/backend/student/services/interfaces/IStudentGetByTokenService.java
El endpoint puede ser accedido solo por un `Student` mediante la URI `GET` `/student`. Devuelve un json como este:
```json
{
"data": {
"id": 14,
"name": "Sebastian",
"lastname": "Barreto",
"dni": "34229337",
"birthdate": null,
"emailTutor": null,
"user": {
"id": 26,
"email": "sebastianbarreto317@gmail.com"
},
"course": {
"id": 1,
"name": "A",
"year": {
"id": 1,
"name": "Primer Año"
}
},
"active": true,
"profile": {
"id": 14,
"selectedBody": {
"id": 7,
"name": "Cuerpo Masculino Rubio",
"image": "https://i.ibb.co/35nhRDZj/4a232cfcd351.png",
"price": 10.00,
"type": "CUERPO",
"available": true
},
"selectedShirt": {
"id": 9,
"name": "Camiseta Azul",
"image": "https://i.ibb.co/twpNS5sC/32be452b338e.png",
"price": 10.00,
"type": "REMERA",
"available": true
},
"selectedHat": {
"id": 1,
"name": …
```
=> Endpoint GetStudentByToken. #227
